AllCops:
  TargetRubyVersion: 2.5
  SuggestExtensions: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Layout/LineLength:
  Max: 120

Style/SpecialGlobalVars:
  Enabled: false
